language: csharp

matrix:
  include:
    - name: Ubuntu
      os: linux
      dist: bionic
      mono: none
      dotnet: 2.1.508
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - RID=linux-x64
    - name: macOS
      os: osx
      mono: none
      dotnet: 2.1.508
      env:
        - RID=osx-x64
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - |
    mkdir -p cblip/build
    pushd cblip/build
    cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
    make -j8 CBlip
    popd

    pushd TroublemakerProxy
    dotnet publish -r $RID -c Release -f netcoreapp2.0 --self-contained true /p:ShowLinkerSizeComparison=true