version: 1.0.0.{build}
branches:
    only:
        - master
        - /\d*\.\d*\.\d*/

init:
    - cmd: git config --global core.autocrlf true

# Environment
image: Visual Studio 2017
clone_depth: 1

install:
    - git submodule update --init --recursive

build_script:
    - ps: |
        New-Item -Type Directory cblip/build -ErrorAction Ignore
        Push-Location cblip/build
        cmake -G "Visual Studio 15 2017 Win64" ..
        cmake --build . --target CBlip --config MinSizeRel
        Pop-Location

        dotnet publish -c Release /p:LinkDuringPublish=false
        Push-Location TroublemakerProxy 
        dotnet publish -r win7-x64 -c Release -f netcoreapp2.0 --self-contained true /p:ShowLinkerSizeComparison=true
        Pop-Location

after_build:
    - ps: Move-Item .\TroublemakerProxy\bin\release\netcoreapp2.0\win7-x64\publish\ TroublemakerProxy_Build
    - ps: Move-Item .\BadNetworkPlugin\bin\release\netstandard2.0\publish\ BadNetwork_Plugin
    - ps: Move-Item .\MessageInterceptorPlugin\bin\release\netstandard2.0\publish\ MessageInterceptor_Plugin
    - ps: Move-Item .\NoCompressionPlugin\bin\release\netstandard2.0\publish\ NoCompression_Plugin
    - ps: Move-Item .\DisconnectionPlugin\bin\release\netstandard2.0\publish Disconnection_Plugin

artifacts:
    - path: TroublemakerProxy_Build
      name: TroublemakerProxy_win7-x64
      type: zip
    - path: BadNetwork_Plugin
      name: BadNetwork_Plugin
      type: zip
    - path: MessageInterceptor_Plugin
      name: MessageInterceptor_Plugin
      type: zip
    - path: NoCompression_Plugin
      name: NoCompression_Plugin
      type: zip
    - path: Disconnection_Plugin
      name: Disconnection_Plugin
      type: zip

deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: "Release $(APPVEYOR_REPO_TAG_NAME) of TroublemakerProxy"
    artifact: TroublemakerProxy_win7-x64, BadNetwork_Plugin, MessageInterceptor_Plugin, NoCompression_Plugin, Disconnection_Plugin
    force_update: true
    auth_token:
        secure: UTRy2ve/9X5iHLIHzvzfwhpprTuhk7tKoete6RfENcFEtSPM1MTP/pCTLZmuYqUT
    on:
        APPVEYOR_REPO_TAG: true