strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
      RID: "linux-x64"
    mac:
      imageName: "macos-10.14"
      RID: "osx-x64"
    windows:
      imageName: "vs2017-win2016"
      RID: "win7-x64"
  maxParallel: 3

pool:
  vmImage: $(imageName)
steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'cblip/build'
      cmakeArgs: '-G "Visual Studio 15 2017 Win64" ..'
    condition: eq(variables['imageName'], 'vs2017-win2016')
    
  - task: CMake@1
    inputs:
      workingDirectory: 'cblip/build'
      cmakeArgs: '-DCMAKE_BUILD_TYPE=MinSizeRel ..'
    condition: ne(variables['imageName'], 'vs2017-win2016')
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'TroublemakerProxy'
      arguments: '-r $(RID) -c Release -f netcoreapp2.0 --self-contained true /p:ShowLinkerSizeComparison=true'