strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      RID: "linux-x64"
      cmakeArgs: "-DCMAKE_BUILD_TYPE=MinSizeRel .."
    mac:
      imageName: "macos-latest"
      RID: "osx-x64"
      cmakeArgs: "-DCMAKE_BUILD_TYPE=MinSizeRel .."
    windows:
      imageName: "windows-2019"
      RID: "win10-x64"
      cmakeArgs: '-G "Visual Studio 16 2019" -A x64 ..'
  maxParallel: 3

pool:
  vmImage: $(imageName)
steps:
  - checkout: self
    clean: true
    submodules: recursive
    
  - task: CMake@1
    inputs:
      workingDirectory: 'cblip/build'
      cmakeArgs: $(cmakeArgs)
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'pushd cblip/build && make -j8 CBlip'
    condition: ne(variables['imageName'], 'windows-2019')

  - task: CMake@1
    inputs:
      workingDirectory: 'cblip/build'
      cmakeArgs: '--build . --target CBlip --config MinSizeRel'
    condition: eq(variables['imageName'], 'windows-2019')

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'TroublemakerProxy'
      arguments: '-r $(RID) -c Release -f net5.0 --self-contained true /p:ShowLinkerSizeComparison=true'